# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "hurlenko/aria2-ariang:1.3.2"
  amd64: "hurlenko/aria2-ariang:1.3.2"
  armv7: "hurlenko/aria2-ariang:1.3.2"
labels:
  org.opencontainers.image.title: "Aria2 + AriaNg (WebUI)"
  org.opencontainers.image.description: "Aria2 Download Manager & AiraNg Web Interfacce All I One Solution."
  org.opencontainers.image.source: "https://github.com/SiriosDev/SiriosDev-HomeAssistant-Add-On/tree/main/aria2ng"
  org.opencontainers.image.licenses: "MIT/Apache License 2.0"
codenotary:
  # signer: "sirioscommercial@gmail.com"