# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Aria2 + AriaNg (WebUI)
version: "1.3.2"
slug: aria2ng
codenotary: "sirioscommercial@gmail.com"
description: "Aria2 Download Manager & AiraNg Web Interfacce All I One Solution"
url: "https://github.com/SiriosDev/SiriosDev-HomeAssistant-Add-On/tree/main/aria2ng"
privileged:
  - "SYS_ADMIN"
  - "DAC_READ_SEARCH"
  - "NET_ADMIN"
arch:
  - armv7
  - aarch64
  - amd64
init: false
devices:
  - "/dev/net/tun"
  - "/dev/sda"
  - "/dev/sdb"
  - "/dev/sdc"
  - "/dev/sdd"
  - "/dev/sde"
  - "/dev/sdf"
  - "/dev/sdg"
  - "/dev/nvme"
  - "/dev/nvme0n1p1"
  - "/dev/nvme0n1p2"
  - "/dev/mmcblk"
  - "/dev/sda1"
  - "/dev/sdb1"
  - "/dev/sdc1"
  - "/dev/sdd1"
  - "/dev/sde1"
  - "/dev/sdf1"
  - "/dev/sdg1"
  - "/dev/sda2"
  - "/dev/sdb2"
  - "/dev/sdc2"
  - "/dev/sdd2"
  - "/dev/sde2"
  - "/dev/sdf2"
  - "/dev/sdg2"
  - "/dev/sda3"
  - "/dev/sdb3"
  - "/dev/sda4"
  - "/dev/sdb4"
  - "/dev/nvme0"
  - "/dev/nvme1"
  - "/dev/nvme2"

map:
  - "media:rw"
  - "config:rw"
  - "share:rw"
  - "ssl"
options:
  dns: "8.8.8.8,1.1.1.1"
  SavePath: "/share/aria2"
  RPCKey: "changethiskey"
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
  ssl: False
  whitelist: "localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16"
schema:
  dns: "str?"
  SavePath: "str?"
  RPCKey: "str?"
  certfile: "str?"
  keyfile: "str?"
  ssl: "bool?"
  whitelist: "str?"
panel_icon: "mdi:progress-download"
ports:
  "8080/tcp": 8080
  "6880/tcp": null
  "6800/tcp": null
ports_description:
  "8080/tcp": "Web UI port (not required for Ingress)"
  "6880/tcp": "6880 Port"
  "6800/tcp": "6800 Port"

image: "hurlenko/{arch}-aria2-ariang"
